### ISSUE TITLE
Server cannot start

### ISSUE THREAD

**Issue by ywiyogo** [LilDojd/gabioinf#85]
Hi,
first of all awesome work that you can deploy this project!
I'd like to learn from your code. After cloning and run `dx  serve --platform fullstack`, the server crashes with this errors:
```
2024-09-02T01:08:58.724189Z  INFO gabioinf: Starting server
thread 'main' panicked at src/main.rs:33:72:
called `Result::unwrap()` on an `Err` value: UnableToLoadIndex("/gabioinf/dist/public/index.html")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1102:23
   4: gabioinf::main::{{closure}}
             at ./src/main.rs:33:53
```
Your readme suggest to setup environment variables, but I don't know which one.

Thanks!

**Comment by LilDojd** [comment]
Hi, thank you for checking out the project. I was on vacation, but will update the readme and address your issue shortly!

**Comment by LilDojd** [comment]
@ywiyogo I have added the example config [here](https://github.com/LilDojd/gabioinf/blob/main/.env.example)

Please check if it works now and feel free to reopen the issue

**Comment by ywiyogo** [comment]
Thanks for adding the env file example.

I created a postgresql database, set the DATABASE_URL and DOMAIN_URL,  run `sqlx migrate run`.
Either starting `./dist/gabioinf` or `dx serve --platform fullstack`, I still see that the backend is panicking.

```
2024-09-08T08:29:18.906275Z  INFO gabioinf: Starting server
thread 'main' panicked at src/main.rs:33:72:
called `Result::unwrap()` on an `Err` value: UnableToLoadIndex("/home/y2/codes/dioxus-learn/gabioinf/dist/public/index.html")
stack backtrace:
   0:     0x5ef48b482775 - std::backtrace_rs::backtrace::libunwind::trace::h23054e327d0d4b55
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5ef48b482775 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cc587407d7f7f64
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
...
  42:     0x5ef48b47667d - std::panic::catch_unwind::h92e02677901e11e4
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  43:     0x5ef48b47667d - std::rt::lang_start_internal::hcee5ed89fc25829a
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:20
  44:     0x5ef48aa46ffc - main
  45:     0x7fb1e8229d90 - <unknown>
  46:     0x7fb1e8229e40 - __libc_start_main
  47:     0x5ef48a86eca5 - _start
  48:                0x0 - <unknown>
```

Unfortunately, I cannot see more debug msgs or compiler errors.

**Comment by LilDojd** [comment]
The server binary expects a particular directory structure right now. I believe this will change on the stable 0.6.0 release, but for now, you should follow the Dockerfile and move dioxus `dist` contents to the same directory the binary is in. This is a fs tree for the docker image that should work:

```
root@84dad47776fd:/usr/local/bin# tree -L 2
.
|-- CV_Georgy_Andreev_barebones.pdf
|-- alchemistry.png
|-- alien_links.css
|-- alien_white.webm
|-- config
|   |-- default.toml
|   |-- development.toml
|   `-- production.toml
|-- favicon.ico
|-- gabioinf
|-- github-mark-white.svg
|-- header.svg
|-- heart.svg
|-- logout.svg
|-- main.css
|-- navbar.css
|-- public
|   |-- CVGeorgyAndreevbarebonespdfcb795661d7fbcfc.pdf
|   |-- CV_Georgy_Andreev_barebones.pdf
|   |-- __assets_head.html
|   |-- alchemistry.png
|   |-- alien_links.css
|   |-- alien_white.webm
|   |-- alienlinkscss8e89085562699296.css
|   |-- assets
|   |-- favicon.ico
|   |-- gabioinf.wasm
|   |-- github-mark-white.svg
|   |-- githubmarkwhitesvga60b7579c3f93a25.svg
|   |-- header.svg
|   |-- heart.svg
|   |-- heartsvg6020f29757dce8a1.svg
|   |-- index.html
|   |-- logout.svg
|   |-- logoutsvgd42e402a963f7941.svg
|   |-- main.css
|   |-- maincss1a09ee2bd040b274.css
|   |-- navbar.css
|   |-- navbarcssedf9e5512a20e7b5.css
|   |-- saucer_divider.svg
|   |-- saucerdividersvgbd46d5f199f423c.svg
|   |-- sesh.JPG
|   |-- seshJPG5ebdd139135b7d3.JPG
|   |-- tailwind.css
|   `-- tailwindcss8d8e7ea35abcc5e0.css
|-- saucer_divider.svg
|-- sesh.JPG
`-- tailwind.css
```
